apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: menu-upload
spec:
  # fires at 01:00, 02:00, 03:00 on Mondays CST => 17:00, 18:00, 19:00 on Sundays UTC
  schedule: "0 17,18,19 * * 0"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: dongfeng-jobs
            task: menu-upload
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 100
          containers:
          - name: menu-upload
            image: ilovelili/dongfeng-jobs:latest
            env:
            - name: DF_ENVIROMENT
              value: dev
            - name: MICRO_REGISTRY
              value: kubernetes
            command: [
              "./server",
            ]
            args:
            - "menu_upload"